### PR TITLE
Added my story

### PR DESCRIPTION
**Pull request by psion**
How I was hired into a large financial company without a college degree.

### CODE REVIEW

**Comment by jkup** [comment]
Thanks so much for adding this! Do you have an avatar we could use? Even just your GitHub one would be great. For design sake I'm just trying to add an avatar to each one.

**Comment by psion** [comment]
Go ahead and use my GitHub Avatar. It's a gravatar image.

**Comment by himaboddupalli** [comment]
I got rejected from NTU in Singapore for an internship after junior year, got rejected by Citi during my job hunt in my senior year. I also got rejected by NVIDIA, Goldman Sachs, The Trade Desk before getting accepted into Salesforce for my internship after the first year of Master's. Worked day and night (along with music classes simultaneously) to defeat rejection. Now, I am an incoming Software Engineer at Salesforce in SF!

**Comment by Lethalmathematix** [comment]
> I got rejected from NTU in Singapore for an internship after junior year, got rejected by Citi during my job hunt in my senior year. I also got rejected by NVIDIA, Goldman Sachs, The Trade Desk before getting accepted into Salesforce for my internship after the first year of Master's. Worked day and night (along with music classes simultaneously) to defeat rejection. Now, I am an incoming Software Engineer at Salesforce in SF!

Don't comment here, m8.
Add your story to src/data/stories.js, and create a PR.

Ez pz for a software engineer. ¯\_(ツ)_/¯

**Pull request closed without merging**
